name = "Material Docs"
license = "MIT"
description = "A material design theme for documentations."
tags = ["material", "documentation", "docs", "google analytics", "responsive"]
features = []
min_version = 0.20

[author]
  name = "Engineerd"

# If porting an existing theme
[original]
  name = "Digitalcraftsman"
  repo = "https://github.com/digitalcraftsman"
